server:
  port: 888

spring:
  application:
    name: job-server
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: always #non_null#non_empty
      time-zone: GMT+8
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 300MB
  datasource:
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    validation-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DatebookHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
#    url: jdbc:mysql://43.130.59.147:31001/seata-at-test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: seata
#    password: seata..123
    url: jdbc:mysql://43.130.59.147:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zhangkun..123
  jpa:
    show-sql: true

#  # 定义quartz的参数 这里的参数在使用stater之后生效，另外不建议使用jdbc存储，这些表是任务调度过程中的临时表 参考tables_mysql.sql
#  quartz:
#    auto-startup: true
#    # 使用数据库作为jobStore
#    job-store-type: jdbc
#    # 默认情况下，配置创建的作业不会覆盖已从持久作业存储中读取的已注册作业。设置为true之后才会覆盖，否则只能删除job之后新增job sysJobService.removeJob sysJobService.addOrUpdateJob
#    overwrite-existing-jobs: true
#    jdbc:
#      # 是否启动时初始化数据库，由于我们自定义了sys_job增加了invok类型和方式，所以不能覆盖
#      initialize-schema: never

# LOGGING
logging:
  level:
    root: info
    org:
      springframework:
        data:
          elasticsearch: debug
  file:
    path: logs
    max-history: 90
    max-size: 1GB